-- TABLE CREATION

create table Customer (
customer_id SERIAL primary key,
first_name VARCHAR(50),
last_name VARCHAR(50),
phone_number VARCHAR(15),
email VARCHAR(100),
address VARCHAR(255)
);

create table Car (
car_id INT primary key,
make VARCHAR(50),
model VARCHAR(50),
year INT,
price DECIMAL(10, 2),
VIN VARCHAR(17) UNIQUE,
is_new BOOLEAN
);

create table Salesperson (
salesperson_id INT primary key,
first_name VARCHAR(50),
last_name VARCHAR(50),
email VARCHAR(100),
phone_number VARCHAR(15)
);

CREATE TABLE Mechanic (
    mechanic_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50)
);

create table Invoice (
invoice_id INT primary key,
customer_id INT,
car_id INT,
salesperson_id INT,
invoice_date DATE,
total_amount DECIMAL(10,2),
foreign key (customer_id) references Customer(customer_id),
foreign key (car_id) references Car(car_id),
foreign key (salesperson_id) references Salesperson(salesperson_id)
);

create table ServiceTicket (
service_ticket_id INT primary key,
car_id INT,
customer_id INT,
service_date DATE,
description text,
foreign key (car_id) references Car(car_id),
foreign key (customer_id) references Customer(customer_id)
);

create table ServiceRecord (
service_record_id INT primary key,
service_ticket_id INT,
mechanic_id INT,
part_used VARCHAR(100),
service_description text,
cost DECIMAL(10, 2),
foreign key (service_ticket_id) references ServiceTicket(service_ticket_id),
foreign key (mechanic_id) references Mechanic(mechanic_id)
);

alter table Customer
	alter column customer_id add generated by default as identity;

alter table Car
	alter column car_id add generated by default as identity;

alter table Salesperson
	alter column salesperson_id add generated by default as identity;

alter table Invoice
	alter column invoice_id add generated by default as identity;

alter table ServiceTicket
	alter column service_ticket_id add generated by default as identity;

alter table Mechanic
	alter column mechanic_id add generated by default as identity;

alter table ServiceRecord
	alter column service_record_id add generated by default as identity;

-- DATA INSERTING
-- into Customer table
INSERT INTO Customer (first_name, last_name, phone_number, email, address) VALUES
('John', 'Doe', '123-456-7890', 'john.doe@example.com', '123 Elm St'),
('Jane', 'Smith', '987-654-3210', 'jane.smith@example.com', '456 Oak St');

--  into Car table
insert into Car (make, model, year, price, VIN, is_new) values
('Toyota', 'Camry', 2021, 25000.00, '1HGCM82633A123456', TRUE),
('Honda', 'Civic', 2020, 22000.00, '1HGCM82633A654321', FALSE);

-- into Salesperson table
insert into Salesperson (first_name, last_name, email, phone_number) values
('Alice', 'Johnson', 'alice.johnson@example.com', '555-123-4567'),
('Bob', 'Williams', 'bob.williams@example.com', '555-987-6543');

-- into Invoice table
insert into Invoice (customer_id, car_id, salesperson_id, invoice_date, total_amount) values
(1, 1, 1, '2024-05-01', 25000.00),
(2, 2, 2, '2024-05-02', 22000.00);

-- into ServiceTicket
insert into ServiceTicket (car_id, customer_id, service_date, description) values
(1, 1, '2024-05-03', 'Oil Change'),
(2, 2, '2024-05-04', 'Tire Rotation');

-- into Mechanic
insert into Mechanic (first_name, last_name) values
('Michael', 'Brown'),
('Laura', 'Green');

-- into ServiceRecord
INSERT INTO ServiceRecord (service_ticket_id, mechanic_id, part_used, service_description, cost) VALUES
(1, 1, 'Oil Filter', 'Oil Change', 50.00),
(2, 2, 'Tire', 'Tire Rotation', 60.00);

-- Creating a strored function for 'Customer' table
create or replace function add_customer(
p_first_name VARCHAR,
p_last_name VARCHAR,
p_phone_number VARCHAR,
p_email VARCHAR,
p_address VARCHAR
)
returns void as $$
begin
	insert into Customer (first_name, last_name, phone_number, email, address)
	values (p_first_name, p_last_name, p_phone_number, p_email, p_address);
end;
$$ language plpgsql;

-- Inserting new data in Customer table using stored function
SELECT add_customer('Sultan', 'Ahmed', '156-434-7890', 'sultan@example.com', '123 sperry Av');
SELECT add_customer('Jack', 'Smith', '987-214-3210', 'jack@example.com', '578 harlem rd');

select * from Customer;
